env:
    browser: true
    node: true
    commonjs: true
    es6: true
extends: 'eslint:recommended'
parserOptions:
    sourceType: module
    ecmaVersion: 8
rules:
    indent:
        - error
        - 4
        - ArrayExpression: off
          SwitchCase: 1
          CallExpression:
            arguments: first
    no-unused-vars:
        - error
        - argsIgnorePattern: ^_$
    no-constant-condition:
        - error
        - checkLoops: false
    semi:
        - error
        - always
    # linebreak-style:
    #     - error
    #     - unix
    # quotes:
    #     - error
    #     - single
