rules:
    indentation:
        - 1
        - size: 4
    property-sort-order: 0
    zero-unit: 0
    single-line-per-selector: 0
    no-ids: 0
    nesting-depth: 0
    leading-zero: 0
    no-color-literals: 0
    no-color-keywords: 0
    placeholder-in-extend: 0
    no-important: 0
