name: homepage
on:
    push:
        branches:
            - master
env:
    CPP: gcc
    CC: gcc
    LD: gcc
    DOIT_NUM_PROCESS: 0
jobs:
    homepage:
        runs-on: ubuntu-latest
        steps:
          - name: checkout repository
            uses: actions/checkout@v2
          - name: install ubuntu requirements
            run: sudo apt-get install -q -y $(< requirements.github.ubuntu.txt)
          - name: install python
            uses: actions/setup-python@v1
            with:
                python-version: 3.8
          - name: setup cache
            uses: actions/cache@v2
            with:
                path: |
                    ~/.cache/pip
                    cache
                    node_modules
                key: ${{ runner.os }}-cache
          - name: install requirements.pip.txt
            run: |
                python -m pip install --upgrade pip
                pip install -r requirements.pip.txt
          - name: doit homepage
            run: doit homepage
          - name: create CNAME
            if: github.repository == 'hat-open/hat-core'
            run: |
                 echo "core.hat-open.com" > build/homepage/CNAME
          - name: deploy
            uses: peaceiris/actions-gh-pages@v3
            with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: ./build/homepage
                publish_branch: gh-pages
                force_orphan: true
