name: main
on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master
jobs:
    main:
        strategy:
            matrix:
                platform:
                    - ubuntu-latest
                    - macos-latest
                    - windows-latest
                python_version:
                    - 3.8
        runs-on: ${{ matrix.platform }}
        steps:
          - name: checkout repository
            uses: actions/checkout@v2
          - name: install python
            uses: actions/setup-python@v1
            with:
                python-version: ${{ matrix.python_version }}
          - name: install requirements.pip.txt
            run: |
                python -m pip install --upgrade pip
                pip install -r requirements.pip.txt
          - name: doit check
            run: doit check
          - name: doit test
            run: doit test
          - name: doit dist
            run: doit dist
          - name: upload artifacts
            uses: actions/upload-artifact@v1
            with:
                name: dist
                path: dist
