name: main
on:
    push:
        branches-ignore:
            - gh-pages
    pull_request:
        branches-ignore:
            - gh-pages
jobs:
    check:
        runs-on: ubuntu-latest
        steps:
          - name: checkout repository
            uses: actions/checkout@v2
          - name: install python
            uses: actions/setup-python@v1
            with:
                python-version: 3.8
          - name: install requirements.pip.txt
            run: |
                python -m pip install --upgrade pip
                pip install -r requirements.pip.txt
          - name: doit check
            run: doit check
    test:
        strategy:
            matrix:
                platform:
                    - ubuntu-latest
                    - macos-latest
                    - windows-latest
                python_version:
                    - 3.8
        runs-on: ${{ matrix.platform }}
        steps:
          - name: checkout repository
            uses: actions/checkout@v2
          - name: install python
            uses: actions/setup-python@v1
            with:
                python-version: ${{ matrix.python_version }}
          - name: install requirements.pip.txt
            run: |
                python -m pip install --upgrade pip
                pip install -r requirements.pip.txt
          - name: doit test
            run: doit test
    dist:
        needs: test
        runs-on: ubuntu-latest
        steps:
          - name: checkout repository
            uses: actions/checkout@v2
          - name: install ubuntu requirements
            run: sudo apt-get install -q -y $(< requirements.github.ubuntu.txt)
          - name: install python
            uses: actions/setup-python@v1
            with:
                python-version: 3.8
          - name: install requirements.pip.txt
            run: |
                python -m pip install --upgrade pip
                pip install -r requirements.pip.txt
          - name: doit dist
            run: doit dist
          - name: upload artifacts
            uses: actions/upload-artifact@v1
            with:
                name: dist
                path: dist
